/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package colonygame.ui;

import colonygame.Main;
import colonygame.game.Person;
import java.util.ArrayList;

/**
 *
 * @author TOM
 */
public class ColonistTracker extends javax.swing.JFrame {

    /**
     * Creates new form ColonistTracker
     */
    public ColonistTracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstColonists = new javax.swing.JList();
        lblId = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        lblDeath = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();

        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("DoB");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));

        lstColonists.setBackground(new java.awt.Color(0, 0, 0));
        lstColonists.setForeground(new java.awt.Color(51, 255, 51));
        lstColonists.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "No Colonists" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstColonists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstColonists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstColonistsMouseClicked(evt);
            }
        });
        lstColonists.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstColonistsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstColonists);

        lblId.setForeground(new java.awt.Color(102, 255, 102));
        lblId.setText("id");

        lblGender.setForeground(new java.awt.Color(102, 255, 102));
        lblGender.setText("gender");

        lblBirth.setForeground(new java.awt.Color(102, 255, 102));
        lblBirth.setText("Birth");

        lblDeath.setForeground(new java.awt.Color(102, 255, 102));
        lblDeath.setText("Death");

        lblState.setForeground(new java.awt.Color(102, 255, 102));
        lblState.setText("state");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBirth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblState)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstColonistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstColonistsMouseClicked
        // TODO add your handling code here:
        String id = lstColonists.getModel().getElementAt(lstColonists.getSelectedIndex()).toString();

        if (!id.equalsIgnoreCase("No Colonists")) {
            Person p = (Person) lstColonists.getModel().getElementAt(lstColonists.getSelectedIndex());

            lblId.setText("id: " + p.getId());
            lblGender.setText("Male: " + p.isMale());
            lblBirth.setText("Birth: " + p.getDOB());
            lblDeath.setText("Death: " + p.getDOD());
            lblState.setText("State: " + p.getState());
        }



        //get the colonist then update the model
        lstColonists.setModel(new javax.swing.AbstractListModel() {
            ArrayList<Person> peps = Main.game.getPeople();

            @Override
            public int getSize() {
                return peps.size();
            }

            @Override
            public Object getElementAt(int i) {
                if(i>=getSize()||i<0){
                    return "No Colonists";
                }
                return peps.get(i);
            }
        });
    }//GEN-LAST:event_lstColonistsMouseClicked

    private void lstColonistsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstColonistsKeyPressed
        // TODO add your handling code here:
        lstColonistsMouseClicked(null);
    }//GEN-LAST:event_lstColonistsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColonistTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColonistTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColonistTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColonistTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColonistTracker().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblDeath;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblState;
    private javax.swing.JList lstColonists;
    // End of variables declaration//GEN-END:variables
}
